package demg2.prog2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dj implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public dj() {
    }

}